### ISSUE TITLE
How can i try with demo key without AWS account?

### ISSUE THREAD

**Issue by hasimyerlikaya** [PDFTron/pdftron-flutter#1] opened 2019-03-08 16:17 UTC
Hi, I want to try your product. But I take an error.
I want to use any pdf link and without aws account.
How can I do this?

`
* What went wrong:
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> Could not resolve com.pdftron:pdftron:6.10.0.
  Required by:
      project :app > project :pdftron_flutter
   > Could not resolve com.pdftron:pdftron:6.10.0.
      > Could not get resource 's3://pdftron-maven/release/com/pdftron/pdftron/6.10.0/pdftron-6.10.0.pom'.
         > The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: 4B6525E2ED63D726; S3 Extended Request ID: x5vt4gP+NVkioxOi9hIK/6kClm1T+p3+ZPHAj9tR3yQLCsowThOSEFi9jhb+Dg4bPGY55QXknNw=)
> Could not resolve com.pdftron:tools:6.10.0.
  Required by:
      project :app > project :pdftron_flutter
   > Could not resolve com.pdftron:tools:6.10.0.
      > Could not get resource 's3://pdftron-maven/release/com/pdftron/tools/6.10.0/tools-6.10.0.pom'.
         > The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: D0F7ED16293D5281; S3 Extended Request ID: 7lXZVbUDuhMsEbo51LbcwBen8F8xTvXsUy8AW//wYYsJO483SQ8GKQZR4cRf1wd/iCbwERQhlvc=)
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org`

**Comment by sgong-pdftron** [comment] 2019-03-26 01:08
@hasimyerlikaya Sorry for the delayed reply. The issue is likely due to missing the correct AWS credentials. You can obtain the credentials here https://www.pdftron.com/documentation/android/guides/flutter/?showkey=true

**Comment by sgong-pdftron** [comment] 2019-04-29 21:09
Closed as issue should be resolved. Re-open if the issue still persist. Thanks.

**Closed by sgong-pdftron** 2019-04-29 21:09 UTC

**Comment by braysonjohn148** [comment] 2019-10-12 21:46
imported it in my pubs (pdftron_flutter=G:\\Flutter SDK\\flutter\\.pub-cache\\git\\pdftron-flutter-7580ce5b0716d4b6809b8e00a992b5f9f077326c\\) but still bring error import 'package:pdftron_flutter/pdftron_flutter.dart';

**Comment by sgong-pdftron** [comment] 2019-10-16 00:28
@braysonjohn148 could you please submit a support ticket here https://www.pdftron.com/form/request with details so we can sort out the issues? Thanks.
